//
//  TestWords.swift
//  TextToSpeech
//
//  Created by Ryan Lintott on 2021-02-05.
//

import Foundation

struct TestWords {
    static let all = Set(testWordsSingleString.split(separator: "\n").map({ String($0) }))
    
    static let allCharacters = Set(testWordsSingleString)
    
    static let allKeyboardCharacters = Set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")
    static let allSpecialCharacters = allCharacters.filter { !allKeyboardCharacters.contains($0) }
    
    private static let testWordsSingleString = """
    ˈdæ-rɛn-ta-ˌmuː-θa
    ˈθɔ-tɛ-rɪ-an
    ˈfɔr-θɪ-an
    ˈfæ-dɛr-ˌliː-tʃə
    ˈfreːɔ-ˌʃɪ-pə
    ˈwrɛntʃ-ˌwiːs
    jɛ-ˈsa-kʌ
    ˈby-dɛn-ˌbɔ-təm
    ˈleːav-ˌhɛl-mɪj
    ˈlæt-ˌræː-də
    ˈprɛ-dɪ-ˌtʃɛ-rə
    ˈreː-tʃə-ˌleːa-zɪ-an
    ˈhɔrs-ˌkrɔft
    jɛ-ˈsɛj-nɪ-an
    ˈfæːxθ
    ˈliːtʃ-ˌsɪr-tʃə
    ˈswæːr-ˌmoːd
    ˈky-nə-ˌθrym
    ˈɪn-ˌhɛɔrd
    ˈkan-dɛl-ˌwɛɔk
    ˈmɪn-ˌdoːm
    ˈθɔrn-ˌræːw
    ˈaːn-ˌha-ga
    ˈgnɔrn-ˌsɔrx
    a-ˈbɛ-rɛnd-liːtʃ
    ˈstɪrk
    ˈfaː-kən-ˌtaː-kən
    jɛ-ˈruː-ma
    ˈlɛnk-tɛn-ˌhæː-tə
    ˈbyːt-lɪ-an
    ˈsoːθ
    ˈjɝː-mə-ˌleːas
    ˈfɹeːɔ-ɹɪj-ˌfɛɹhθ
    ˈθɹiːst-ˌhɝj-dɪj
    ˈɛ-vɛ-tə
    ˈwlɔt
    ˈfɝɹn-jɛ-ˌflɪt
    ˈhɛals
    ˈstɪ-tʃɛl
    ˈɛaɹ-vɛθ-ˌmædʒ
    ˈhæːθ-ˌfɛld
    ˈwɛ-lɛɹ
    ˈdæj-ˌθɛɹ-litʃ
    ˈiː-ɹɛn-jɛ-ˌloː-ma
    ˈnɛa-ɹʌ-ˌwɹɛntʃ
    ˈsɪb-ˌlʌ-vʌ
    ˈwɛj-ˌfeː-ɹɛnd
    ˈhæ-ɹɪŋ-ˌtiː-ma
    ˈla-gʌ-ˌsiːθ
    jɛ-ˈleːɔ-mɔd
    ˈwɔɹd-ˌhɔɹd
    ˈwɔɹd-ˌlɔ-ka
    ˈwlɪ-tɪj-ˌfæst
    ˈboːk-ˌhuːs
    ˈtɛa-gɔɹ
    ˈwɛ-zɛnd
    ˈleːa-θɔɹ
    ˈfeː-lə-ˌleːas
    ˈblɛn-kan
    ˈfneːɔ-zʌŋ
    ˈɛalh
    a-ˈdwɛl-lan
    ˈstæf
    ˈfɔlk-ˌlaːɹ
    ˈfɔl-jɪ-an
    a-ˈtɛɔ-ɹɪ-jɛnd-ˌliːtʃ
    ˈʃɛak-ˌdoːm
    ˈʌn-ˌʃɛ-θɪj
    ˈniːw-ˌva-ɹa
    ˈθɛn-nɪŋ
    ˈfɹeːɔ-ɹɪ-ˌmoːd
    ˈfɛɔh
    ˈblɛɔh
    ˈsʌnd-ˌɹɛ-tʃɛd
    ˈland-ˌhlaː-vɔɹd
    ˈboːk
    a-ˈdiː-lɪ-jɪ-an
    ˈgaːl-zɛ-ɹə
    ˈbɛl-tʃɛd-ˌsweːɔ-ɹa
    ˈʌn-ˌsweː-tə
    ˈheːah-ˌkɝ-niŋ
    ˈmuːθ
    ˈwɝn-ˌbeːam
    ˈsʌn-ˌwlɪ-tɪ-gɔst
    ɝmb-ˈklɝp-pan
    ˈhæ-ɹɪŋ
    ˈpɔz-lɪŋ
    jɛ-ˈpalm-ˌtwiː-jəd
    ˈswæː-zɛn-də
    ˈæp-sɛn
    ˈdɔdʒ-a
    ˈjeːɔ-gʌθ-ˌknoː-zəl
    ˈhɛ-ɹə-ˌgɹiː-ma
    jɛ-ˈmeːθ-jɪ-an
    ˈspɹɪŋ
    ˈsʌn-na
    ˈiː-θə-ˌliː-tʃə
    ˈsaː-wɛl-ˌʃɛat
    ˈsankt
    ˈɪn-wɪt-ˌflaːn
    ˈaː-nʌŋ-ga
    ˈfɛɔɹm
    ˈknæp-lɪŋ
    ˈbɝl-dan
    ˈgna-gan
    ˈblæːd
    ˈsmeːa-ˌθan-kɔl-nɛs
    ˈmɛ-ɹə-ˌwiːf
    ˈhɛɔ-ɹʌ-ˌwɛaɹg
    ˈʃɪp
    ˈland-ˌbuː-nɛs
    ˈwɝn-ˌdɹeːam
    ˈhɹeːθ
    ˈkɹæft
    ˈʌn-jɛ-ˌvɹæː-jɛ-liːtʃ
    ˈhɹeːɔ
    ˈwɪl-zʌm-ˌliː-tʃə
    jɛ-ˈmaːh
    ˈswiːn
    ˈwʌn-dɹɪ-an
    ˈhwɛalf
    ˈɛak-səl-jɛ-ˌstɛa-la
    ˈɹɛj-nɪ-an
    ˈha-sʌk
    ˈjeːan-ˌpæθ
    ˈswɪtʃ-ˌdoːm
    ˈhɛ-ɹə-ˌgaŋ
    ˈɹæː-jə
    ˈmæːj-ˌbʌɹh
    ˈheːah-ˌlʌ-və
    ˈflaːh
    ˈlʌd-ˌjɛat
    ˈ tʃeːn
    ˈjɛɔnd-ˌɹeː-kan
    jɛ-ˈlɔk-kɪ-an
    ˈɛv-nan
    ˈfɹeːɔlz-ˌjɛ-va
    ˈ tʃɪ-tʃɛn
    ˈwɛl-ˌhwæːɹ
    ˈfeːɔnd-ˌʃɛa-θa
    ˈdæj
    ˈhɛɔɹθ
    ˈuːɹ
    ˈwɔɹd-ˌsaː-wɛ-ɹə
    ˈɔl-vɛnd-ˌmɛ-ɹə
    ˈeːv-stan
    ˈtʃɪl-ɪtʃ
    ˈɛl-lɛn-ˌak-sə
    ˈgnɔɹ-nɪ-an
    ˈga-dɛ-ɹʌŋ
    ˈwaː-ɹɪj
    ˈθɪj-nɛn
    jɛ-ˈɹɝː-man
    ˈleːh-tan
    æt-ˈlæː-dan
    ˈɹaːd
    ʌn-ˈaː-mɪɹ-ɹɛd
    ˈwɝnd-lə
    ˈwiːj-ˌbɔ-ɹa
    ˈjiːt-sɪ-an
    ˈloːk-ɪ-an
    ˈjeːɔ-gʌθ-ˌfɛɔɹh
    ˈbɛa-dʌ-ˌhɹæ-jəl
    ʌn-jɜ-ˈstæθ-θɪj
    ˈtɛld-ˌwɝɹh-ta
    ˈswɛɔ-tɔ-lʌŋ
    ˈwɝn-ˌwɛɔ-ɹɔd
    ˈdæj-ˌkuːθ
    ˈkɝ-nɛ-ˌman
    ˈwan-kɔl
    ˈbɝːk-nɪ-an
    ˈhɔ-pɪ-an
    ˈheːah-ˌstɹɛŋ-θʌ
    ˈheːa-vɔd-ˌswiː-ma
    ˈɛn-də
    ˈhæːθ-ˌsta-pa
    ˌa-ˈhɹɛd-dan
    ˈtæ-jəl-ˌhæːɹ
    ˈbɪ-lɛ-ˌwɪt-nɛs
    ˈbɔks
    ˈmɪd-ˌwɪn-təɹ
    ˈswiːj-ˌtiː-ma
    ˈliːj-ˌlɔk
    ˈflɛt-ˌwɛ-ɹɔd
    ˈhɛɔl-stɔr
    ˈæːɹ-ˌæːt
    ˈhɛɔɹθ-ˌbak-ən
    ˈtiːɹ-ˌwɪ-nə
    ˈwʌl-dɔɹ-ˌjɪ-vʌ
    ˈan-ˌtɛ-vən
    ˈglɪ-da
    jɛ-ˈwɪz-ˌliː-tʃɛ
    a-ˈɹæː-man
    ˈtʃɪld-ˌkɹa-dɔl
    ˈkan-dɛl-ˌtɹeːɔ
    ˈhɹan-ˌfɪʃ
    ˈleːan-ˌjɪ-va
    ˈhɹɪŋ-ˌfiŋ-gər
    ˈmɪd-dɛl-ˌfiŋ-gər
    ˈgɹɝɹ-ɹan
    ˈpɔt
    ˈaːɹ-ˌwɛɔɹθ
    ˈuːθ-ˌwɪ-tɪ-gʌŋ
    ʌn-ˈgniː-θɛ
    ˈfɪɹst-ˌmɛaɹk
    ɛl-ˈθeːɔ-dɪj-nɛs
    ˈjeːɔ-tan
    ˈhæː-ɹih-tɛ
    ˈkan-dɛl-ˌtwɪst
    jɛ-ˈhuːs-ˌʃɝ-pɛ
    ˈwɪk-ˌdæj
    ˈtɪ-tɛ-lʌŋ
    ˈhɛ-tɛ-lɪtʃ
    ˈθæːɹ-ˌʌn-dɛɹ
    ˈhɛɔɹt-ˌlʌ-vɛ
    ˈʃɪ-t͡ʃɪŋ
    ˈfaːm-jɪ-an
    ˈtɪɹ-gɪŋ
    ˈstɛaɹk-ˌhɛaɹd
    ˈtoː-ˌeːa-kan
    ˈæt-ˌbɹɛg-dan
    ˈsɪ-jɛ-ˌjɪɹd
    ˈwɪ-θɛɹ-ˌkɹɪst
    ˈʌn-ˌmʌɹn-liː-t͡ʃɛ
    ˈsɛɔ-vɔn
    ˈlæː-ɹɪŋ-ˌmæː-dɛn
    jɛ-ˈtɪŋ-ˌkɹæft
    ˈtwæː-mɪŋ
    ˈneːah-ˌlæː-kan
    ˈsand-jɛ-ˌwɛɔɹp
    ˈmɛ-ɹɜ-ˌstɹɛn-gʌ
    ˈwɛl-ˌdoːn-nɛs
    ˈtʃeːas-nɛs
    ˈnɪɹwθ
    ˈhaːl-gɪ-an
    ˈoː-ga
    ˈɛ-jɛs-fʌl-ˌliː-tʃə
    ˈwɪ-t͡ʃɛ-ˌdoːm
    ˈɹiːp-ˌtiː-ma
    ˈhær-vɛst-ˌwæː-ta
    ˈjiː-zəl
    ˈhæɹ-vɛst-liːt͡ʃ
    ˌʌn-dɛɹ-ˈkɹam-mɪ-an
    ˈɔl-vɛnd
    ˈɹuːm-ˌjɪ-va
    ˈpɹuːt-ˌswaŋ-ɔɹ
    ˈhæn-nɛ-ˌbɛl-lɛ
    ʌn-ˈaː-ɹæv-nɛd-ˌliː-tʃɛ
    ˈgɔd-ˌkʌnd-liːt͡ʃ
    ˈʃʌ-lan
    ˌʌn-bɛ-ˈwɪl-lɛd
    ˈæl-mɛz-ˌæ-kɛɹ
    ˈɹɪf-tɛ-ɹɛ
    ˈhæː-θɛn-ˌstɝɹk
    ˈjɝ-vʌ-ˌθan-kʌŋ
    ˈlaŋ-ˌtwɪ-dɪj
    ˈgliːw-ˌkɝn
    bɛ-ˈʃɛat-ˌwɝɹ-pan
    ˈlɔk-ˌstaːn
    ˈθɹɔ-zəm
    ˈjɛl-lan
    ˈwɪk-ˌwɛɔɹk
    ˈfoː-ɹa-ˌʃeːa-wʌŋ
    ˈknɪht-ˌwɛ-zɛn-də
    ˈjɪlp-ˌʃɛa-θa
    ˈhand-ˌgaŋ
    ˈæʃ-ˌwiː-ga
    ˈla-pɪ-an
    ˈboːt-ˌdæj
    ˈkwɝl-la
    ˈmoːd-ˌblɪnd
    ˈnɔt-ˌjɛɔɹn
    ˈga-ˌgaː-tɛs
    ˈlaːf
    ˈɛ-vɛn-ˌnɪht
    ˈsɪb
    ˈlaːk-nɪ-an
    ˈfɹam-ˌfæ-ɹɛld
    ˈjeːɔ-ˌʃɛaft
    ˈfɪʃ-nɔθ
    ˈkaːf
    ˈdɹɔh-tɔθ
    ˈjɝː-man
    ˈæv-tɛɹ-ˌfɝl-gan
    ˈbɹeː-mɛ
    ˈwɪd͡ʒ-ˌkɹæft
    ˈsaːɹ-ˌkwɪ-dɛ
    ˈhaːɹ
    ˈweːa-ˌmoːd
    ˈlaː-wɛɹ-t͡ʃɛ
    ˈand-jɪt-ˌfʌl-liːt͡ʃ
    ˈwiː-glʌŋ
    ˌa-ˈɹiː-zan
    ˈpɹæt-tɪj
    ˈwiː-kan
    ˈɹiːp-ˌtiː-ma
    ˈsaː-ɹɪj
    ˈweː-θɛ
    ˈhla-gɔl
    ˈwɛaɹg-ˌbɛ-ɹɛn-dɛ
    ˈɔs-tɛɹ-ˌhlaːf
    ˈgnæt
    ˈboːk-ˌhɔɹd
    ˈjɪ-wɪ-an
    jɛ-ˈfɹɛt-tan
    ˈθeːɔ-wɪŋ
    ˈgliːw-ˌbɝ-dɛ-nɛz-tɹɛ
    bɛ-ˈbɛɔɹ-gan
    ˈlaːst-ˌwɛaɹd
    ˈlaːst
    ˈfæːɹ-ˌstɪ-t͡ʃɛ
    ˈfeː-θɛ-ˌmʌnd
    ʌn-ˈhɛaɹm-ˌjɛɔɹn
    ˈjɪ-pɪ-an
    ˈwlɪsp
    ˈwɛj-ˌbɹaː-dɛ
    ˈhɔh-ˌmoːd
    ˈla-tɪ-an
    ˈpɹas
    ˈjɛɔl-ka
    ˈjɛa-vɛl
    ˈswiː-jɛn
    ˈbleːd-ˌhwæt
    ˈmɛ-ɹɛ-ˌtɔɹ
    fʌl-ˈlæːst-an
    ˈbaːn-ˌkɔ-va
    ˈhɹeːɔh
    ˈlaŋ-ˌtɔh
    ˈwæjn-jɛ-ˌwæː-də
    ˈθuː-ma
    jɛ-ˈʃɛl-dɔd
    ˌʌn-ˈfɹɪd͡ʒ-ɛn-dɛ
    ˈɹɪht-ˌand-swa-ɹʌ
    ˈsmeːa-ˌwɝɹh-ta
    ˈɛd-ˌjɝl-dɛnd
    ˈsɪ-vɛ-θa
    ˈsoːθ-ˌsa-gɔl
    ˈsɛt-ˌhɹæ-jəl
    ˈwiːd-ˌbɹaːd
    ˈmaːn-ˌdɹɪntʃ
    ˈtʃeː-lan
    ˈswɛaɹm
    ˈɛal-ˌtæːw-liː-tʃɛ
    ˈhɝht-ˌjɝ-vʌ
    ˈaː-ˌkwɛɔɹ-na
    ˈoː-mɪj
    ˈæɹ-tʃə-ˌdɪ-aː-kɔn
    ˈswɜɔɹ-kan
    ˈfloːd-ˌwɝlm
    ˈpɔɹt-ˌstɹæːt
    ˈʌn-dɛɹ-ˌhniː-gan
    ˈæl-mɛz-ˌleːɔht
    ˈfɛ-la-ˌmoː-dɪj
    ˈeːaɹ-jɛ-ˌbland
    ˈhwɝɹv-lʌŋ
    ˈlɪmp-ˌliː-tʃɛ
    ˈæː-ˌvɛst-nɛs
    ˈmæ-zɛn
    ˈwɛn-dan
    ˈswɛ-vɛl
    ˈwɛl-jɛ-ˌkweːm-nɛs
    ˈæ-ˌrɛa-və
    ˈmoːd-jɛ-ˌθank
    jɛ-ˈbɝr-man
    ˈswɛv-nɪ-jɛnd
    ˈtʃeːol
    ˈta-bʌ-lə
    ˌeal-də-ˌeal-də-ˈvæ-dɛr
    ˈsʌ-mɛr-ˌlaŋ
    ˈfreːo-ˌdoːm
    ˈha-ɹa
    jɛ-ˈmɪ-mɔɹ
    ˈflɔk
    ˈfɛɔɹh-ˌjɪ-va
    ˈsmeːah
    ˈa-ɹɛ-wə
    ˈwiːɹ-ˌtɹeːɔ
    ˈɪn-ˌgaŋ
    ˈʃɹɝn-tʃə
    ˈbɹɝ-nə-ˌleːɔ-ma
    ˈɛɔɹ-mɛn
    ˈtiːd-ˌfa-ɹa
    ˈæːɹ-bɛ-ˌθoːht
    ˈfant-ˌwæ-tɛɹ
    ˈɪn-ˌtɪŋ-ga
    ˈgoː-ma
    ˈnaː-ˌhwæ-θɛɹ
    ˈælf-ˌkɝn
    ˈsæː-ˌland
    ˈpɛ-tɛɹ-ˌzɪ-lɪ-jə
    ˈbɛ-ɹɪ-ə
    ˈgɹeː-nə-ˌhæː-wɛn
    ˈɹa-gʌ
    ˈuːht
    ˈɪn-jɛ-ˌmɝnd
    ˈboːk-ˌkɝn
    ˈfɛ-la-ˈiː-dɛl-ˌspɹæː-tʃə
    ˈæ-veːst
    ˈfɪʃ-ˌpoːl
    ˈɹɛ-gɔl-ˌwɛaɹd
    ˈnɪθ-ɛɹ-gaŋ
    bɛ-ˈlɛdʒ-an
    ˈbloː-tɛ-ɹə
    ˈɪn-ˌhɪɹd-man
    ˈliːj-ˌspɪ-wɔl
    bɛ-ˈga-lan
    ˈwʌn-dɔɹ-bɛ-ˌbɔd
    ˈsɪntʃ-ˌjɪ-vʌ
    ˈʃɔl-ˌman
    ˈmoː-dɔɹ-ˌlʌ-vʌ
    jɛ-ˈlɛŋ-ə
    ˈsta-lɪ-an
    ˈlɝft-ˌʃɛa-θa
    ˈælf-ˌθɔ-nə
    ˈat-tɔɹ-ˌkɔp-pa
    ˈpluːm-ˌblæːd
    ˈlak-tʌ-ka
    ˈpɪ-zə
    ˈaːɹ-ˌjɝ-va
    ˈstɛal-kʌŋ
    ˈæːn-lɪtʃ
    ˈniːθ-ˌdɹa-ka
    ˈɛɔɹ-mɛn-ˌgɹʌnd
    ˈlaːk-nʌŋ
    jɛ-ˈwɪt-ˌleːast
    ˈθeːɔd-ˌkweːn
    ˈlaːɹ-ˌlɛast
    ˈgʌ-ma
    ˈɹɛjn-ˌwæ-tɛɹ
    jɛ-ˈkɝː-θan
    ˈwɪdʒ
    ˈɹɪht-ˌdoːn-də
    fɔɹ-ˈswɪ-gan
    ˈɹɪb-ˌspaː-kan
    ˈwɹɛn-kan
    ˈsnɔ-tɔɹ-ˌʃɪ-pə
    ˈguːθ-ˌkweːn
    ˈlæː-tʃə-ˌfɪŋ-gəɹ
    ˈmuːθ-ˌfɹeːɔ
    ˈɔn-ˌgaŋ
    ˈbeːɔ-ˌtʃɛɔɹl
    ˈɛal-ˌwɪh-ta
    ˈha-na
    ˈhwoː-sta
    ˈfɹoː-vɔɹ
    wɪθ-ˈeːa-stan
    ˈsiːθ-ˌda-gas
    ˈswɛ-jɛl-ˌkan-dɛl
    ˈfɪɹ-jɛn-ˌgaːt
    ˈwɪst
    ˈsɪks
    ˈɛaɹn
    ˈnɪht-ˌjɛŋ-ga
    ˈsmeːa-ˌwɹɛntʃ
    ˈsɪn-ˌnɪht
    ˈswɪn-kan
    ˈsnɔt
    ˈgal-dɔɹ-ˌwɔɹd
    ˈfeːɔn-dʌlf
    ˈdæj-ˌɹɪ-ma
    ˈfɹɪθ
    ˈwiːn
    ˈiː-dɛl-ˌjɛɔɹn
    ˈwɛ-dɛɹ-ˌtaː-kɛn
    ˈlɔt-ˌwɹɛntʃ
    ˈlɪn-dɛz-ˌvaɹ-nɛa-ˌlan-dɪŋ
    ˈsnɝː-tan
    ˈʃiːn-ˌlaːk
    ˈeːaɹ-ˌklæːn-zɪ-ɛnd
    jɛ-ˈfɝː-zan
    ˈælf-ˌsɪ-dɛn
    jɛ-ˈbɝr-man
    ˈlɔv-ˌjɛɔɹn
    ˈkuː-ˌtæ-jɛl
    ˈbeːɔd-jɛ-ˌneːat
    ˈfɔlk-ɪʃ
    ˈkuː-ˌmɪ-dʒə
    ˈsmɪθ
    jɛ-ˈswɪntʃ-ˌdæj
    ˈkɹæt
    ˈleːak-ˌtuːn
    ˈɔɹt-ˌjɛaɹd
    ˈtʃɪld
    ˈɛaɹ-vɔθ-ˌhwiːl
    ˈfɝɹ-wɪt-ˌjɛɔɹn
    ˈaːk
    ˈga-vɔl-ˌhɛɔɹd
    ˈeːɔh
    ˈfɛn-ˌfʌ-jɛ-las
    ˈdʌst-ˌdɹɛntʃ
    ˈbæk-ɛs-tɹə
    ˈsʌnd-ˌhɛŋ-gɛst
    ˈkuː-ˌhɔɹn
    ˈmoː-na
    ˈlɛah-tɛɹ
    ˈhlɛah-tɔɹ
    oː-ˈjɛŋ-gɛl
    ˈfɹeːɔnd-ˌlʌ-vʌ
    ˈiː-dɛl-ˌjɝlp
    ˌɔ-vɛɹ-ˈjɛŋ-ga
    ˈwæjn
    ˈmuːs
    ˈɔ-vɛɹ-jɛ-ˌdɹɝntʃ
    ˈkɝ-niŋ
    ˈsɪntʃ
    ˈgaːl-ˌfɹeːɔl-zas
    ˈɹoːt
    ˈʃɛaft
    ˈtʌŋ-gɔl-ˌkɹæft
    ˈtʌŋ-gɔl-ˌjɪm
    ˈwɝɹt-ˌdɹɛntʃ
    ˈwʌn-dɛn-ˌstɛv-na
    ˈʃɪp-pan
    ˈfɹɪθ-ˌkan-dɛl
    ˈwɹɛntʃ
    ˈɛnd-ˌlɛɔ-van
    ˈsɪ-jɛl
    ˈgaːt
    ˈgaŋ
    ˈkwɛθs-θuː-ˌlaː
    ˈʃɪp-ˌwɝrh-ta
    ˈjɝɹ-stan-ˌdæj
    ˈgaːɹ-ˌleːak
    ˈwɹɛntʃ-ˌwiːs
    ˈkoː-vɪn-tʃəl
    ˈbeːɔ
    ˈfeːa
    ˈhʌnd
    ˈwɪ-θɛɹ-ˌbɹɛ-ka
    ˈɹɛɔɹd
    ˈgaːst-ˌkɝ-niŋ
    ˈjɛaɹd
    ˈfloːd-ˌwʌ-dʌ
    ˈwɝn
    ˈɛn-nə-ˌleːak
    ˈkuː-ˌeːa-jə
    ˈsæː-ˌæl-vɛn
    ˈkuː-ɛ-ˌmɛ-za
    aː-ˈwɪht
    ˈwɝɹm-ˌba-zʌ
    ˈleːɔd-ˌwɝn
    ˈfæ-dɛ-ɹɛn
    ˈsʌn-ˌhaːt
    ˈwɛɔ-lɔk-ˌɹeːad
    ˈwɛɔ-lɔk
    ˈsnak
    ˈhaːɹ-ˌwɛŋ-gə
    ˈwɝɹt-ˌjɛaɹd
    ˈkuː-ˌtʃɛalf
    ˈhuːs
    ˈflæːʃ-ˌhɔɹd
    ˈhaː-dɔɹ
    ˈwɝɹt-ˌstɛntʃ
    ˈbɹeːad
    ˈmɛ-rə-ˌkan-dɛl
    ˈhʌŋ-gɔɹ-ˌlæː-wə
    ˈsʌn-ˌbɛɔɹht
    ˈleːak
    ˈhluːd
    ˈkuː-ˌhɝɹ-də
    ˈfɛŋ
    ˈwɝɹt-ˌtuːn
    ˈdɹʌnk-ɛn-ˌjɛɔɹn
    ˈfɛɔɹh-ˌhɔɹd
    ˈmɛ-ɹə-ˌhuːs
    ˈwɛɹ-ˌjɛŋ-ga
    ˈbʌ-tɛ-ɹə
    ˈgliːw-ˌbeːam
    ˈɔ-vɛɹ-ˌlʌ-vʌ
    ˈæp-pɛl-ˌtuːn
    ˈsɝm-bɛl-ˌwɝn
    ˈkuː-ˌmɛɔ-lʌk
    ˈmɛ-dʌ-ˌdɹɪntʃ
    ˈmɔɹ-gɛn-ˌkɔl-la
    ˈɝːθ-ˌlaːd
    ˈhɛaɹ-pə
    ˈmɛ-tɛɹ-ˌkɹæft
    ˈdɹeːam-ˌkɹæft
    ˈɔf-ˌka-lɛn
    ˈwʌl-dɔɹ
    ˈbeːah-ˌjɪ-vʌ
    ˈhwæt
    ˈjɪ-vʌ
    ˈdæj-ˌɹeːd
    ˈmɔɹ–gɛn
    ˈsmɪθ-ˌkɹæft
    ˈwʌn-dɔɹ-liːtʃ
    ˈgaːt
    ˈkoːv-ˌgɔ-das
    ˈdɹeːam-ˌhæ-bɛn-də
    ˈʃɛand
    ˈmɔɹ–gɛn-ˌdɹɛntʃ
    ˈwɔl-kən-jɛ-ˌhnaːst
    ˈæːɹ-ˌmɔɹ–gɛn
    ˈkuː-ˌbʌ-tɛ-ɹə
    ˈwɝɹt-ˌgæl-strə
    ˈtʃɝː-zə
    ˈwɔɹd-ˌleːan
    aː-ˈkæ-glɔd
    ˈʌn-dɛɹn
    ˈna-ka
    ˈmɛ-ɹə-ˌgɹɔ-ta
    ˈspɪtʃ
    ˈtʃɪ-tʃɛn
    ˈkuː-ˌbɝː-ɹə
    ˈjɛɔh-sa
    ˈɝmb-ˌspɛn-nɪŋ
    ˈwɝɹt
    ˈgliːw
    ˈʃɛntʃ
    ˈwɔɹθ-ˌa-pʌl-dɛɹ
    ˈhɛɔ-ɹʌ-ˌswɛal-wə
    ˈhwæ-ləs-ˌeː-θɛl
    ˈɝːθ-ˌlɪ-da
    ˈbɛntʃ-ˌsɪ-tɛnd
    ˈwɔl-kən-ˌfa-ɹʌ
    ˈliːv-ˌwɝn
    ˈɛ-vɛn-jɛ-ˌmæk-ka
    ˈfuːl-ˌstɪn-tʃɛn-də
    ˈliːv-jɛ-ˌtwɪ-nan
    ˈfɪʃ
    ˈstɹæːl-ˌbɔ-ɹa
    ˈθɹɔ-wɛnd
    ˈleːɔ
    ˈɹank-ˌstɹæt
    ˈa-pʌl-dɛɹ
    ˈnɛ
    ˈjeːa
    ˈfæ-dɛɹ
    ˈmoː-na
    ˈfɹeːɔ-gan
    ˈʌn-ˌwɛ-dɛɹ
    ˈkɔst-nʌŋ-ˌstoːw
    ˈlɝft-ˌflɔ-ga
    ˈfʌ-jɛl
    ˈhwiː-tɛl
    ˈwam
    ˈlɝft-ˌwɝn
    jɛ-ˈswɪntʃ-ˌdæj
    ˈæː-ˌlæː-ɹɛn-də
    jɛ-ˈkɔ-ɹɛn-ˌʃɪ-pə
    ˈliːj-ˌdɹa-ka
    ˈɛnd-ˌwæɹk
    bɛ-ˈtwɛɔ-nʌm
    jɛ-ˈswɪntʃ
    ˈa-pɹeː-lɪs-ˌmoː-naθ
    ˈɪ-dɛs
    ˈiːs
    ˈɔn-ˌstɛ-pan
    ˈswiːn-ˌhɪɹ-də
    ˈʃɝ-tə-ˌfɪŋ-gəɹ
    ˈwɪn-tɛɹ-ˌstʌnd
    jɛ-ˈkɔ-ɹɛn
    ˈwiːd-ˌwɛ-gas
    ˈlɛnk-tɛn
    ˈga-vɔl-ˌfɪʃ
    ˈswɪntʃ
    ˈwɪn-tɛɹ-ˌtiːd
    ˈmæː-tɪŋ
    ˈtwɛlf-ta-ˌdæj
    ˈsɪn-ˌtʃɛald
    ˈfɹeːɔnd-ˌspeː-dɪj
    ˈaːn-ˌflɔ-ga
    ˈhɔɹs
    ˈfeː-ɹɛn-də
    jɛ-ˈgaf-ˌspɹæː-tʃə
    ˈleːav-ˌwɝɹm
    ˈwɛɔl-tʃɛn-ˌɹeːad
    ˈtuːn
    ˈʃeːap
    bɛ-ˈsɛn-kan
    ˈwæ-vɛr-ˌgaŋ-gə
    ˈdoːm-ˌjɛɔɹn
    ˈfɹeːɔnd-ˌlʌ-vʌ
    ˈɛ-vɛn-nɝs
    ˈwɪn-tɛɹ
    be-ˈθɛn-tʃə ˌθuː
    ˈbeːɔ-ˌmoː-dɛɹ
    ˈɛal-ɹa-ˌsank-ta-ˌsɝm-bɛl
    ˈɛ-jɛs-ˌgɹɪ-mə
    ˈaːn-ˌeː-jəd
    ˈpɝn-ka
    ˈwʌlf-heːa-vɔd-ˌtɹeːɔ
    ˈeːɔ-ɹɛd-ˌtʃɪst
    ˈbæv-tan-ˌsɪt-tɛn-də
    ˈbæf-ta
    ˈbɛɔrn-ˌθreːat
    ˈbʌrx-ˌsæl
    ˈpa-pɔl-ˌstaːn
    ˈɹaː
    ˈbaː
    ˈheːah-ˌɛŋ-gɛl
    ˈstɔk
    ˈstoːk
    ˈwʌl
    ˈpɛ-nɪŋ-ˌwɛɔrθ
    ˈbeːax-ˌjɪ-va
    ˈpɪ-stɔl
    ˈwaŋ-ˌstɛ-də
    ˈgɔd-ˌspɛl
    ˈba-na
    ˈfylst
    ˈstɪj-ˌwɛaɹd
    ˈstɪj
    ˈfɔld-ˌwɛj
    ˈgɔld-ˌfɪŋ-gəɹ
    ˈɛlp
    ˈθrym
    ˈæ-jɛr-ˌvɛl-ma
    ˈsweːj-ˌhleːɔ-θɔr
    ˈhɛɔ-vɔn-ˌhroːf
    bɛ-ˈhɛ-lan
    ˈseː-lɔst
    ˈsneːɔ-mə
    ˈsʌn-dɔɹˌjɛŋ-ga
    ˈdæj-ˌkuːθ
    ˈoːθ-ˌʃuː-van
    ˈbaːn-ˌvæt
    ˈhæɹ-vɛst-ˌmoː-naθ
    ˈhaː-lɪj-ˌmoː-naθ
    ˈleːɔv-ˌtæː-lə
    ˈkɔr-θɛr
    ˈæ-θɛ-lɪŋ
    ˈeː-stɪj
    ˈθeːɔd-ˌwiː-ga
    ˈha-zʌ-ˌpaː-da
    ˈwɛl-θʌŋ-gɛn
    ˈhaːs-ˌsweː-jə
    ˈwaŋ-ˌbɛard
    ˈwʌ-dʌ-ˌbleːd
    ˈdæj-ˌfæ-stɛn
    jɛ-ˈiː-kan
    ˈky-nə-ˌstoːl
    ˈɛl-lɛn-ˌroːf
    ˈsweːt-ˌmɛ-tə
    ˈgɔld-ˌjɪ-va
    ˈwiːf
    ˈspɪw-ˌdɹɛntʃ
    ˈsʌn-dɔr-ˌfreːɔ-doːm
    ˈswoːl
    ˈlʌf-sʌm
    ˈdɪ-aː-kɔn
    ˈhɛɔ-vɔn-ˌfʌ-gɔl
    ˈdɔt
    ˈhæɹ-vɛst
    ˈlɛɔ-θʌ-ˌkræf-tɪj
    ˈswɛtʃ
    jɛ-ˈwɛl-jɪ-an
    ˈman-ˌθwæː-rə
    ˈweːɔd-ˌmoː-naθ
    ˈhlaːf-ˌmæs-sə
    ˈuː-rɪj-ˌlaːst
    ˈwiːs-fæst
    ˈhɛa-θʌ-ˌroːf
    ˈhɔlt-ˌwʌ-dʌ
    ˈdʌ-gʌθ
    ˈdæj-ˌkan-dɛl
    ˈaːn-ˌsta-pa
    ˈsteːam
    jɛ-ˈhɛ-vɪ-jɪ-an
    ˈɛr-blɛad
    ˈsʌn-dɔɹ-jɛ-ˌkɝnd
    ˈdryxt
    ˈleːɔv-ˌtæː-lə
    ˈhaː-ta-ˌba-θan
    ˈleːav-ˌʃɛad
    ˈfyrn-jɛ-ˌfliː-ta
    ˈsweːt-ˌsweː-jə
    ˈoːθ-hɪl-də
    ˈpan-θɛr
    bɪ-ˈhlyx-han
    ˈkɔrn-ˌwʌr-ma
    ˈæːj-hwaː
    ˈbɛa-dʌ-ˌroːf
    ˈkɔɹ-ˌsnæːd
    ˈpa-nɪtʃ
    ˈfʌ-jɛl-ˌtɪm-bɛr
    ˈɛ-pɛ-ˌjɪt-sʌŋ
    ˈuː-rə-ˌlɛn-dɪʃ
    ˈmæːd-ˌmoː-naθ
    ˈjɪuː-lʌ-lɪŋ
    ˈæv-tɛ-ɹa-ˌliː-θa
    ˈhaz-wɪj-ˌfɛ-θɛ-ra
    ˈæːn-liːtʃ
    ˈaːt-tɔɹ-ˌʃɛa-θa
    ˈneːɔ-tan
    ˈpan-ˌmɛ-tə
    ˈwʌ-dʌ-ˌæl-vɛn
    ˈdyːr-lɪŋ
    ˈtʌ-nɛ-tʃə
    ˈeː-stɪj
    ˈdæ-jɛs-ˌeːa-jə
    ˈsteː-nan
    ˈwɹæːt-liːtʃ
    ˈmɪk-sən
    ˈfɹeːa-ˌmæː-ɹə
    ˈhuː-θə
    jɛ-ˈmɛt-fæst
    ˈwɪl-ˌkʌ-ma
    ˈsʌn-dɔɹ-jɛ-ˌkɝnd
    ˈsnuː-də
    ˈʃɝl-tʌ-mɛnd
    ˈlɪnd-ˌplɛ-ga
    ˈgɔ-mɛl
    toː-ˈwɹɛ-kan
    ˈɛarh-ˌfa-ɹʌ
    ˈgæːst-ˌhaː-lij
    ˈdɹa-ka
    ˈaːn-ˌsta-pa
    ˈdɔɹ-wɪt-ˌtʃɛa-stər
    ˈwɛar-dɪ-an
    ˈæ-ɹa-ˌliː-θa
    ˈand-ˌwɹaːθ
    jɛ-ˈʃeːa-dan
    ˈflæ-θə-ˌkamb
    ˈɛaɹd
    ˈɹɝ-zəl
    ˈfɛɔɹ-ˌlɔnd
    ˈflaːn
    jɛ-ˈkɝnd
    ˈhɝ-jə-ˌmeː-θə
    ˈgɹa-ma-tɪʃ-ˌkɹæft
    ˈlɪnd-ˌwɛɔ-ɹʌd
    ˈtɛɔ-ɹʌ
    ˈfɹɪ-θə-ˌleːas
    ˈθuːf
    ˈsɛɔ-nɔθ
    ˈwiːj-ˌgaːɹ
    ˈgɹɪŋ-gan
    ˈɹʌ-stɪj
    ˈkoːl-ˌpɝt
    ˈhɛ-ɹə-ˌsiːθ
    ˈθɹɝːθ-ˌbɔɹd
    ˈɹɝʃ-ˌɹiː-θɪj
    ˈsʌ-mɛɹ
    ˈwʌlf
    ˈwoːθ-ˌkɹæft
    jɛ-ˈdiː-θan
    ˈdoːm-ˌwɛɔɹ-θʌŋ
    jɛ-ˈʃa-pɛn-nɝs
    ˈbeːam
    ˈhɹeː-mɪj
    ˈθɹɪ-mɪl-tʃə-ˌmoː-naθ
    ˈdæj-ˌwɛɔɹk
    ˈwiːj
    ˈɹæːd
    ˈɹɝː-jʌŋ
    ˈmaɹ-man-ˌstaːn
    ˈbeːn-ˌtiːd
    ɪn-ˈstæ-pəs
    ˈtʃɛm-pa
    ʌn-ˈsoːf-tə
    ˈʃɪl-vɔɹ
    ˈbleːɔ-ˌɹeːad
    ˈblæk
    ˈgɹeː-nə
    ˈdʌn
    ˈhæː-wɛn
    ˈha-zʌ
    ˈgɹæːj
    ˈjɝl-dɛn
    ˈjɛɔ-lɔ
    ˈɹeːɔd
    ˈhɪw
    ˈʌn-ˌsnɝ-tɹɔ
    ˈhæːl
    ˈɛaɹm-ˌtʃɛa-ɹɪj
    jɛ-ˈnɪp
    ˈmɪs-ˌlɪmp
    ˈbɛɔɹk
    ˈtɛalt
    ˈmɔɹ–gɛn-ˌseːɔk
    ˈeːa-stɛɹ-ˌmoː-naθ
    bɛ-ˈklɝ-pɪŋ
    ˈɹɝʃ-ˌbɛd
    ˈɔɹ-ˌtɹuː-wʌŋ
    ˈneː-θan
    ˈæj
    ˈhɛaɹ-dɪŋ
    ˈhæː-lʌ
    ˈʌn-ˌsmɛɔ-ɹʌ-wɪj
    ˈeːa-ˌfɪʃ
    ˈfæ-ɹɝld
    ˈɛm-ˌnɪht
    ˈiːs-ˌtʃɛald
    ˈɪɾθ-lɪŋ
    ˈfɝːɹ-ˌwɝlm
    ˈmaɹ-tɝɹ-ˌra-kʌ
    ˈnæd-dɹə
    mɪs-ˈʃɹɛn-tʃə
    ˈhleːɔ
    ˈmaːn-ˌwɔɹd
    ˈkɔl-lɔn-ˌkɹoːh
    ˈfɝɹ-wɪt
    ˈfɝːst-jɛ-ˌbeːat
    ˈfɛɔɹ-ˌwɛj
    ˈmɪs-ˌlaːɹ
    ˈɛh
    ɪn-ˈfɹoːd
    ˈɹeːɔ-tan
    ˈmɪ-ɹɪθ
    ˈsɪ-jɛl
    ˈɛ-jɛ-za
    ˈhɹeːθ-ˌmoː-naθ
    ˈhlɝː-da
    ˈfeːɔɹ-θəs-ˌfoːt
    ˈɛl-lɛn-ˌtɹeːɔ
    ˈtam
    ˈwæ-tɛɹ-ˌʃɪ-pə
    ˈbɛa-dʌ-ˌkaːf
    ˈθɛ-jən
    ˈkɔ-lɪ-an-dɹə
    ˈhwiːt
    ˈlɛɔɹ-nʌŋ-ˌkɹæft
    ˈfɪ-ɹɪ-jɛnd-ˌstɹeːam
    ˈtɛɔ-zʌ-ˌspɹæːtʃ
    ˈmɔld-ˌhɹeː-ɹɛn-də
    ˈsweːɔ-ˌɹiː-tʃə
    ˈɔɹ-θank-ˌbɛnd
    ˈsoːθ-ˌjɪd
    ˈlʌ-vʌ
    ˈmoːd-ˌbɝz-gʌŋ
    ˈswiːθ-ˌhwæt
    ˈpɝt
    ˈgaːst-jɛ-ˌɹɝː-nə
    ˈslɪ-dɔɹ
    ˈhɝ-jə-ˌkɹæft
    ˈhɹʌ-zə
    ˈseːf-tə
    ˈlɝft
    ˈspɛaɹ-ka
    ˈkɔ-hɛ-tan
    ˈkoː-va
    ˈsɔl-ˌmoː-naθ
    ˈeːad-nɛs
    ˈsnaːw
    ˈwoː-də-ˌwɪst-lə
    ˈfɛ-la-ˌfɹeːk-nə
    ˈhɔɹd-ˌlɔ-ka
    ˈmiːl-ˌpæθ
    ˈsæː-ˌæːl
    ˈgæɹs
    ˈwoː-dən-ˌdɹeːam
    ˈkɔɹn-jɛ-ˌsæː-lɪj
    ˈhwɪɹ-və-ˌpoːl
    jɛ-ˈdɔf
    ˈhleːɔ-tan
    ˈsʌn-ˌsɛt
    ˈhɛaɹm-ˌtaːn
    ˈɛl-lɔɹ-ˌfuːs
    ˈmɛ-tɔd
    ˈɪɹ-ɹə-ˌmoːd
    ˈpɹeːɔwt-ˌhwiːl
    ˈsʌ-gʌ
    ˈɹæː-dɛls
    ˈwɹa-θʌ
    ˈwɔɹd-ˌsɪ-jə
    ˈpɹuːt
    ˈɹɝː-nə-ˌman
    ˈglæs-ˌhlʌ-tɔɹ
    ˈwoːd-ˌliː-tʃə
    ˈɹæː-də-ˌman
    ˈhɛ-ɹə-nɛs
    ˈsʌn-ˌwlɪ-tɪj
    ˈæv-tɛ-ɹa-ˌjeːɔ-la
    ˈwɔɹd-ˌbeːɔt
    ˈhleːɔ-θɔɹ-ˌkwɪ-də
    ˈbɹeːɔst-ˌtʃɛa-ɹʌ
    ˈjɪ-tʃɛl-jɛ-ˌbland
    ˈswɛɔɹd-ˌwɝɹh-ta
    ˈhɔɹd-ˌwɝn
    ˈhɹaːn
    ˈwɪn-tɛɹ-ˌʃuːɹ
    ˈmɔɹ–gɛn-jɛ-ˌbɛd-tiːd
    ˈʌn-jɛ-ˌmɛt-ˌtʃɛald
    ˈwɪn-tɛɹ–ˌdæj
    ˈmoːd-ˌsɛ-va
    ˈɹɝː-jan
    ˈwɔɹd-ˌhleːɔ-θɔɹ
    ˈhwɝɹft
    ˈan-ˌmoːd
    ˈmɔɹ–gɛn-ˌstɛɔ-ra
    ˈglɛŋ
    ˈɹɝ-nə-ˌwæjn
    aː-ˈstɝ-ɹɪ-an
    ˈɔ-vɛɹ-ˌtʃɛald
    ˈbɹoː-θɔɹ
    ˈswɛɔ-stɔɹ
    ˈtoː-ˌhɝht
    ˈmoːɹ-ˌsta-pa
    ˈtʃɛa-vɛɹ
    ˈpæl
    ˈma-pʌl-ˌtɹeːɔw
    ˈfɹɔm-ˌva-ɹʌ
    ˈwɛɔ-ɹɔld-ˌkɹæft
    ˈæ-ɹa-ˌjeːɔ-la
    ˈpʌ-mɪtʃ-ˌstaːn
    ˈmɛɔks
    ˈhɛalz-ˌbɹɝ-nɪ-jə
    ˈwæːɹ-ˌlɔ-ga
    ˈɔk-sna-vɔɹd
    ˈwɔɹd-ˌwiːs
    ˈfɹɔm-ˌhwɛɔɹ-van
    ˈʌn-ˌtɝː-dɹə
    ˈhɛal-ˌstaːn
    ˈpæ-jɛl
    ˈdwɛɔɹχ
    ˈhwɛm
    ˈtʃɛah-ˌhɛ-tʌŋ
    ˈʃiːɹ
    ˈhɛalz-ɹə-ˌfɛ-θɛɹ
    ˈpɹæt-tɪj
    ˈwɪ-θɛɹ-ˌwɛŋ-gɛl
    ˈfɹɔm-ˌkɝn
    ˈʌn-ˌhɔl-da
    ˈwɔɹd-ˌwɝn-zʌm
    jɛ-ˈfæl-zi-an
    ˈpɹeːɔst
    ˈwʌ-nʌŋ-ˌstoːw
    ˈbɛd-ˌklaːθ
    ˈpuː-tʃɛl
    ˈfɹɔ-ma-ˌwæl-ta
    ˈwɔɹd-ˌsnɔ-tɔ-ɹʌŋ
    ˈhɛalz-ˌmɛ-nə
    ˈbɛ-dan-fɔɹd-ˌʃiːɹ
    ˈbloːt-ˌmoː-naθ
    ˈdwɪ-mɔɹ
    ˈdeːaθ-ˌʃuːa
    ˈhɛl-ˌknɪht
    ˈʌn-ˌman
    ˈa-ˌglæːk-wiːf
    ˈa-ˌglæː-ka
    ˈdɹa-ka
    ˈɛ-lɛn-ˌgæst
    ˈgɹʌnd-ˌwɝɹ-jɛn
    ˈʃʌk-ka
    ˈdeːɔ-vɔl-ˌʃiːn
    ˈhɛl-ˌruː-nə
    ˈɔɹk-ˌθɝɹs
    ˈeːɔ-tɛn
    ˈdeː-mɔn
    ˈwɪn-tɛɹ–ˌfɝl-lɛθ
    ˈwoːɹ-ˌha-na
    ˈhɛals-ˌfaŋ
    ˈwɛɔ-ɹɔld
    ˈɛnt
    ˈweːɔd
    ˈfɝɹn-ˌʃɛa-θa
    ˈhweːɔl
    ˈbæk-ˌslɪ-tɔl
    ˈwʌn-dɔɹ
    ˈhlɛah-tɔɹ-ˌsmɪθ
    ˈɪ-jɪl
    ˈmæːd-ˌla-kʌ
    ˈpɝ-fan
    ˈjɝ-tə-ˌsæːl
    ˈsɪ-jə
    ˈbɛɔɹh-ˌhlɪθ
    ˈfɔlm
    ˈhwɛɔp
    ˈʌn-ˌɹæː-dən
    ˈfɔl-gɔθ
    ˈmɔɹ–gɛn-ˌdɹɛntʃ
    ˈhwɛɹ-ˌhwɛ-tə
    ˈkweːn-ˌfʌ-gɔl
    ˈkweːn
    ˈdɹɝntʃ-ˌhɔɹn
    ˈdæj-ɹeːd-ˌsaŋ
    ˈdæj-ˌɹeːd
    toː-ˈæ-tiː-kan
    ˈkwɛɔɹn
    ˈdæj-ˌmæːl-ˌʃeːa-wɛ-ɹə
    ˈdæj-ˌmæːl
    ˈɛ-zɔl
    ˈjɝs-təɹn-liːtʃ-ˌdæj
    ˈjɝst-ˌɛɹn
    ˈtɹah-taθ
    ˈskɹæf
    ˈwaːk-ˌmoːd
    ˈjeːan-ˌkɝ-mə
    ˈkal-wəɹ
    ˈkalk-ˌɹand
    ˈɹand
    ˈkalk
    ˈgɔd-ˌsɪb
    ˈtaː-kən-ˌbɛ-ɹɛnd
    ˈkaːv-ˌʃɝ-pə
    ˈslɪt-ˌkwɛalm
    ˈmɛ-ɹə-ˌgɹʌnd
    ˈbɛɔɹht-ˌbloː-wɛn-də
    ˈhleːɔɹ-ˌʃɛa-mʌ
    ˈtʃɪ-pə
    ˈwan-ˌspeː-dɪj-nɛs
    ˈsmæl-ˌθɛaɹ-mas
    ˈhɛɔ-ɹʌ-ˌkʌm-bʌl
    ˈbla-də-zɪ-an
    ˈwæː-pɛn-ˌθɹa-kʌ
    ˈlʌŋ-gɛn
    ˈbeːɔ-ˌgaŋ
    ˈfɝɹd-ˌhwæt
    ˈdeːaθ-ˌweː-ɹɪj
    ˈkaː-zɛɹ-ˌdoːm
    ˈkaɹl-ˌkat
    ˈkwa-ba
    ˈgɹiː-ma
    ˈstæp-pə-ˌʃoːh
    jɛ-ˈdwæːs-man
    ˈwan-ˌfɛaks
    ˈkɹiː-stɛl-ˌmæːl
    ˈblaː-kɛɹn
    ˈtʃɛɔ-ɹɪj
    ˈkuː-ˌwɛaɹm
    ˈstæɹ-ˌblɪnd
    ˈdɔlh
    ˈgɹeːɔt-ˌhɔɹd
    ˈsæː-ˌjɛŋ-ga
    jɛ-ˈθɝld
    ˈfɝɹd-ˌleːɔθ
    ˈʌn-dɛɹn
    jɛ-ˈdwɔl-ˌbɪ-ʃɛɔp
    ˈsmæː-tə-ˌjɝl-dɛn
    ˈdwæː-ʃan
    ˈbɝː-mə
    ˈtʃɛn-nɪŋ-ˌstoː
    ˈwæl-ˌɹuːn
    ˈfɹɪ-θɔ-ˌwɛ-ba
    ɔn-ˈdɹæː-dan
    ˈtiːɹ-ˌeːa-diːj
    ˈæːɹ-ˌdæj
    ˈhɹæːw
    ˈdɹɝː-ˌɪ-dʒə
    ˈdɹɝː-ˌman
    ˈwʌ-dʌ-ˌɹeːtʃ
    ˈɛɔ-vɔɹ-ˌkʌm-bɔl
    ˈstæɹ-lɪŋ
    ˈsmeːah
    ˈwæ-tɛɹ-ˌɝːθ
    ˈgɹeː-tɪŋ-ˌhuːs
    ˈstæv-ˌkɹæv-tɪj
    ˈboːk-ˌstæf
    ˈdeːaθ-ˌdɹɛ-pə
    ˈduːn-ˌhʌ-nɪj
    ˈda-rɛθ-ˌlaː-tʃɛn-də
    ˈwoː-ma
    ˈɹɔθ-ˌhʌnd
    ˈmɝnd-bɝɹd-nəs
    ˈhɪld-ˌvɹʌ-ma
    ˈlʌŋ-gɹə
    ˈθɹɔ-wʌŋ
    ˈæf-stɪj
    ˈhɛt-tɛnd
    ˈblaːst-ˌbɛlg
    ˈæl-ˌfɝlk
    ˈbɹɪm-ˌfʌ-jəl
    ˈɹɔ-dɔɹ
    ˈhɪld-ˌbɛd
    ˈbɔ-təl-ˌweː-la
    ˈblɪtʃ-ə-tʌŋ
    ˈmɪd-sʌ-mɛɹ
    ˈkaɹ-leːas-nəs
    ˈdɹeːam
    jɛ-ˈfɝl-lɪŋ
    ˈhɹoː-θɔɹ
    ˈbɔɹχ-ˌhand
    ˈaːɹ-ˌsmɪθ
    ˈθɪŋ-jɛ-ˌmɛaɹk
    ˈɹiːtʃ-sɪ-an
    ˈdeːaθ-ˌdɛ-nʌ
    ˈɝmb-ˌsɪt-tɛnd
    ˈhɪld
    ˈhwæl-ˌwɛj
    ˈleːɔd-ˌhwæt
    ˈbeːan-ˌbɹɔθ
    ˈnɔɹθ-ˌθʌ-nɔɹ
    ˈdeːaθ-ˌfɪ-ɹɛn
    ˈfnæː-ɹɛ-tan
    ˈmɛ-ɹə-ˌstɹæːt
    ˈwɔɹd-ˌsam-nɛ-ɹə
    ˈmɛd-ˌmɪ-tʃəl
    ˈmɝɹθ-ɹʌŋ
    ˈmɝnd-jɪ-an
    ˈtɪl-ˌmoː-dɪj
    ˈbɹɪm-ˌlaːd
    ˈgɹɔɹn-ˌhɔf
    fɔɹ-ˈha-ban
    ˈlaːm
    jɛ-ˈliːf-fæ-stan
    ˈmeːd
    a-ˈblɛnd
    ˈheːa-vɔd-ˌjɪm
    ˈhɝl
    ˈwæl-ˌhɹeːɔw-liː-tʃə
    ˈwʌl-dɔɹ-jɛ-ˌflɔ-jɛ-na
    ˈtɛɔl-ˌθɝ-ɹəl
    ˈhɛɔɹ-tə
    ˈwa-θə-ma
    ˈsoːθ-fæst-nɛs
    ˈhɝ-jə-ˌwælm
    ˈheːa-vɔd-ˌhɹæ-jəl
    ɔn-ˈdɹæː-dan
    ˈeːθ-jɛ-ˌzɝː-nə
    aː-ˈblæːst
    ˈheːa-vɔd-ˌgɔld
    ˈwæl-ˌgɹɪm
    ˈdɝ-zɪj
    ˈdɹɝn-tʃə-ˌleːan
    ˈbɛɹ-stɪŋ
    ˈbʌɹg-ˌwɛal
    ˈheːah-ˌkleːɔ-va
    ˈbɹɪm-ˌgæst
    ˈtʃɪɛɹ
    a-ˈwɛj-jɛ-ˌwɪ-tə-nəs
    ˈwaːχ-ˌhɹæ-jəl
    jɛ-ˈwɹɪk-səl
    ˈgleːaw-liː-tʃə
    ˈsæː-ˌbaːt
    ˈtɔ-ɹɛn-ˌiː-jə
    ˈheːa-vɔd-ˌhɛb-ba
    ˈɝːθ-jɛ-ˌwɪn
    ˈhɛ-ɹə-ˌpaθ
    ˈsʌnd-ˌhɛlm
    ˈbɹɝdʒ
    ˈfæ-θəm
    ˈmʌdʒ-ˌwɝɹt
    ˈgæst-ˌhɔf
    bɛ-ˈzuː-pan
    ˈwaː-wa
    fɔɹ-ˈlɪ-jɛɹ-ˌliː-tʃə
    ˈwɪt-leːas
    ˈsæː-ˌgɹʌnd
    ˈtɔɹd-ˌwɪ-vəl
    ˈbɛntʃ-ˌθɛl
    ˈθɝɹz-tɪj
    ˈsta-θɔl-ˌfæst
    ˈwlɪ-tə-ˌʃiː-nə
    ˈduː-və-ˌdɔ-pa
    ˈtɔɹn
    ˈsweːj-ˌdɝ-nə
    ˈɝː-θʌŋ
    ˈflɛaɹ-dɪ-an
    ˈfɹeːɔ-gan
    bɛ-ˈnɛm-nan
    ˈmɛ-tɛɹ-ˌwɝɹh-ta
    ˈteːɔn-ˌliːj
    ˈtɛm-pəl
    ˈmɪd-ˌdæj
    ˈsæː-ˌwʌ-dʌ
    ˈdeːɔ-vɔl-ˌseːɔk-nɛs
    ˈglæs
    ˈfɔld-ˌhɹeː-ɹɛn-də
    ˈbloːst-ma
    ˈeːa-gan ˈbɹɝh-təm
    ˈhlɝːp
    ˈfɛŋ-ˌnɛt
    ˈwʌl-dɔɹ-jɛ-ˌwɛɔɹk
    ˈsʌnd-jɛ-ˌbland
    ˈæɹs
    ˈɹæː-də-ˌʃɛa-mɔl
    ˈnæ-kəd
    ˈɔn-ˌθɹæk
    ˈmɛ-ɹɪ-jɛn-ˌdæj
    ˈfla-kɔɹ
    ˈla-gʌ-ˌstɹeːam
    ˈɔ-vɛɹ-ˌjɪ-tɔl-nɛs
    ˈwa-zə-ˌʃɪ-tə
    ˈsmɪθ-ˌbɛlg
    ˈhwaː-stɹʌŋ
    ˈmɛ-dʌ-ˌhɛal
    ˈwaː-θɔl
    ˈswɝlt
    ˈlʌ-vɪ-ɛnd
    ˈflæːʃ-bɛ-ˌsmɪ-tɛn-nɛs
    ˈdoːm
    ˈmɪ-tʃɛl-ˌspɹɛ-tʃɛn-də
    ˈhɹan-ˌɹaːd
    ˈweːn
    ˈhɝːθ
    ˈla-gʌ-ˌstɹæːt
    ˈhɔlm
    ˈguːθ-ˌwɛaɹd
    ˈwoːh-jɛ-ˌstɹeːɔn
    ˈsɪ-jə-ˌmeː-tʃə
    ˈhwæːɹ-ˌhwɛ-ga
    ˈɝːθ-ˌlaːf
    ˈmoːn-ˌseːɔk
    ˈhɛɔɹt-ˌʃɹæf
    fɔɹ-ˈliː-θɛd-nɛs
    ˈmɛ-dʌ-mʌŋ
    ˈglæ-zɛn-ˌeːa-jə
    ˈhʌŋ-gɔɹ
    jɛ-ˈfoːɹ-wɔɹd
    ˈwɪn-stɹə ˈsæː-ˌhʌnd
    ˈfeː-nɪks
    ˈmɔɹ–gɛn-ˌtiːd
    ˈdeːaθ-ˌsɛ-lə
    ˈhʌnd-ˌwɛalh
    ˈwɪlm
    ˈdeːɔɹ
    ˈmæː-ɹə
    ˈgɔd-ˌwɛb
    ˈhɛ-ɹə-ˌtɔ-ga
    ˈsaːm-ˌkwɪtʃ
    ˈθʌɹh-ˌθɝ-dan
    ˈdɪʃ
    ˈeːa-gɔɹ-ˌstɹeːam
    ˈsmɪθ
    ˈnɝ-tɛn-nɛs
    ˈflæːʃ-ˌæːt
    ˈeːaj-ˌhɹɪŋ-as
    ˈwaːɹ
    ˈɔ-vɛɹ-ˌɝːθ
    ˈhand-ˌsɛaks
    ˈfɛn
    ˈbɝɹ-jɛn
    ˈka-lɪtʃ
    ˈθɹɝm-ˌwɛal-dɛnd
    ˈwæ-tɛɹ-ˌɛ-jɛ-za
    ˈhuːz-ˌboːn-da
    ˈhnɛ-ʃə
    ˈtʃɪn-ˌtoːθ
    ˈhuː-ɹʌ-ˌθɪŋ-ga
    ɔn-ˈdɹɝːz-liːtʃ
    ˈwam-fʌl
    ˈmɪd-dan-ˌjɛaɹd
    ˈɔn-ˌsæ-gʌŋ
    ˈsæː-ˌæl-vɛn
    ˈfɝɹn-ˌjeːa-ɹa
    ˈslæːp-ˌweː-ɹɪj
    ˈeːa-dɪj
    ˈwɪn-tɛɹ-jɛ-ˌgaŋ
    jɛ-ˈmɝ-nə ˌθuː
    jɛ-ˈɹɝː-nʌ
    ˈsa-dɔl-ˌbɛɔɹht
    jɛ-ˈveːɹ-ˌlæː-kan
    ˈsɝm-bɛl-ˌweː-rɪj
    ˈwæs ˌhæl
    jɛ-ˈbeːd-ˌstoːw
    ˈwoːθ-ˌkɹæft
    ˈsɝm-bɛl-ˌgaːl
    ˈdeːɔp-ˌhɝ-dɪj
    ˈsɔɹh-leːas
    ˈjɛɔnd-ˌʃiː-nan
    ˈjeːaɹ-ˌmaɹ-kɛt
    ˈjʌŋ-lɪŋ
    ˈfɔɹst
    ˈwɪn-tɛɹ-ˌɹæː-dɪŋ-boːk
    ˈtaː-kən
    ˈmɛ-dʌ
    jɛ-ˈθɹɪŋ
    ˈhiːw-ˌɹæː-dɛn
    ˈgɹeː-tɪŋ-ˌwɔɹd
    ˈwa-vʌŋ-ˌstoːw
    ˈsæː
    ˈhlaː-vɔɹd-ˌzwɪ-ka
    ˈlɔt-wɹɛntʃ-ˌtʃeːast
    ˈmɔɹ–gɛn-ˌmɛ-tə
    ˈwɪht-ˌwa-ɹə
    ˈsteːɔɹ-ˌman
    ˈmoːd-ˌlʌ-vʌ
    ˈɪn-wɪt-ˌsɛa-ɹɔ
    ˈmɛ-ɹə
    ˈsnɝ-trɔ-ˌhuːs
    ˈwiːn-ˌtɪ-bər
    ˈsɛ-lɛ-ˌdɹeːam
    ˈɔf-fɹʌŋ-ˌspɪtʃ
    ˈhwɛɹ
    ˈjɛɔ-vɔn
    ˈaːk-ˌmɛ-lʌ
    a-ˈkoː-lɪ-an
    ˈfloːd-ˌɝːθ
    ˈθæːɹ-ˌɹɪh-tə
    ˈuːht-ˌflɔ-ga
    ˈgæɹz-ˌhɔp-pa
    ˈmɪ-tʃɛl-ˌdoːɛnd
    ˈwɪn-tɛɹ-ˌtʃɛa-ɹij
    ˈmæ-jɛn-ˌwʌ-dʌ
    ˈnɔs-ˌθɝ-ɹəl
    ˈælf-ˌʃiː-nʌ
    ˈteːa-gan
    ˈjeːaɹ
    ˈmoːd-ˌkɹæf-tɪj
    ˈʃɛa-mɔl
    ˈheːa-vɔd-lɪŋ
    ˈbeːɔ-ˌbɹeːad
    ˈdʌst-ˌʃeːa-wʌŋ
    ˈlɔ-pɝ-stɹə
    ˈuːht
    ˈɛl-lɛn
    ˈwɪt
    ˈlɔv-ˌjɛɔɹ-nɔst
    ˈɛal-ɹa ˈhaːl-jɛ-na ˈæː-vɛn
    ˈdeːɔ-vɔl
    ˈθɝɹs
    ˈgaːst
    ˈwɪ-tʃə-ˌkɹæft
    ˈmɪs-sɛn-ˌliː-tʃə
    ˈwɝn-ˌwɝɹt
    ˈwɝɹd
    jɛ-ˈneːa-ˌlæː-kan
    ˈmɪ-dʒa
    ˈhwɛɔɹv-ˌbaːn
    ˈgɹɪ-mə-tʌŋ
    ˈbɹæː-mɛl-ˌbɛ-ɹɪ-ə
    ˈbɹæːθ
    ˈwæl-ˌmɪst
    ˈsɛjl-ˌɹaːd
    ˈʌn-ˌwɝn-sʌm-nɛs
    ˈswɛɔɹ-ˌbeːa
    ˈha-gɔl-ˌstaːn
    ˈtɪn-tɹɛj
    ˈʃɪp-jɛ-ˌbɹɔk
    ˈwɛ-dɛɹ
    bɛ-ˈsteː-man
    ˈtweːɔ-ˌman
    ˈhɛa-lɪtʃ
    ˈheːa-liːtʃ
    ˈhʌks-liː-tʃə
    ˈjɪm-ˌstaːn
    ˈɛɔɹθ-ˌstɝ-ɹʌŋ
    ˈgaɹ-ˌsɛdʒ
    ˈmɪlt-sʌŋ
    ˈʌn-ˌwɛak-sən
    ˈfloːd
    ˈkaːv-liː-tʃə
    ˈɛaɹn
    ˈhɝ-zə
    jɛ-ˈgɹɛ-mɪ-an
    ˈhɹæ-vən
    ˈfa-ɹɔθ-ˌhɛŋ-gɛst
    ˈbɹɔg-dɛn-ˌmæːl
    ˈsʌ-mɛɹ-ˌsɛl-də
    ˈmɛ-ɹə-ˌtʃɪst
    ˈflɔt-ˌman
    ˈnæ-jəl
    jɛ-ˈhɹɔ-dɛn
    ˈɪn-wɪt-ˌhlɛm
    ˈwiːj-ˌbɪl
    ˈɛak-səl-jɛ-ˌspan
    bɛ-ˈswɝ-lɪ-an
    ˈbɹɪm-ˌwɝlm
    ɪtʃ
    ˈæːɹ-jɛ-ˌwɪn
    ˈwɛ-dɛɹ-ˌkan-dɛl
    jɛ-sɝː-nə
    ˈæː-ɹɛst
    ˈθʌɹh-ˌdriː-van
    ˈhɪl-də-ˌgɹaːp
    ˈmɛaɹk-ˌsta-pa
    ˈglæːm
    ˈɛa-lʌ-ˌʃɛɔp
    ˈswaː-tan
    ˈwɔɹd-ˌkwɪ-də
    jɛ-ˈbɝɹd-ˌdæj
    ˈtɹeːɔw-ˌlʌ-vʌ
    a-ˈtʃɛɔɹ-van
    ˈdeːaθ-ˌbeːam
    ˈwɛɔ-ɹɔld-ˌnɝt
    ˈhɹɛ-θɛɹ-ˌlɔ-ka
    ˈfa-ɹɔθ
    ˈknɝ-san
    ˈhɪl-də-ˌjɪ-tʃɛl
    ˈmɛɔlk
    ˈfiː-vɛl-ˌkɝn
    ˈwlɪ-tɪj
    jɛ-ˈbeːɔɹ-ˌʃɪ-pə
    ˈæt-ɝː-wan
    ˈhɛ-ɹə-ˌwoː-za
    ˈhæ-zəl
    ˈʌn-ˌwɛaɹ-nʌm
    ˈɛaɹd-ˌsta-pa
    jɛ-ˈmɛl-tan
    ˈbɹæ-jɛn
    ˈeːɔ-tɛn-ˌwɛaɹd
    ˈswɛal-wə
    ˈʌn-jɛ-læː-ɹɛd
    ˈbaːn-ˌlɔ-ka
    ˈdɹɝː
    ˈkʌm-bɔl
    ˈɛl-ˌθeːɔ-dɪj
    jɛ-ˈlaːk
    ˈæp-pɛl
    ˈhɛl-ˌtɹæf
    ˈkɝ-nɪŋ-ˌdoːm
    ˈwɪ-nə-ˌleːas
    ˈbɹɪm-ˌstɹeːam
    ˈdwɔl-ˌkɹæft
    ˈhɝ-jə-ˌbliː-θə
    ˈhlaːf
    ˈflæːʃ-ˌha-ma
    ˈɪn-jɛ-ˌθank
    ˈeːa-ˌland
    ˈsɪn-ˌsnæd
    ˈgɹam-ˌhɝj-dɪj
    ˈbɹɪm
    ˈfɛɔɹ-ɹan-ˌkʌ-mɛn
    ˈmɛaɹk-ˌland
    ˈbeːɔd-jɛ-ˌɹɛɔɹd
    ˈlaŋ-gʌŋ-ˌhwiːl
    ˈaːn-wɪn-tɹə-ˌkɝ-nɪŋ
    ˈwɪld-ˌdeːɔɹ
    ˈɔ-vɛɹ-ˌhɝjd
    ˈsɛalt-ˌɝːθ
    ˈweː-dɛn-ˌhɛɔɹt
    ˈhɔlt
    ˈman-ˌdɹeːam
    ˈmɛ-tə-ˌθɛaɹ-vɛn-də
    bɛ-ˈsmiː-tan
    ˈkɔɹn
    ˈsɛlf-ˌdeː-ma
    ˈliːtʃ-ˌha-ma
    ˈgɔld-ˌwɝɹt
    ˈniːd-ˌθɛaɹf
    ˈlɪ-vɛɹ
    ˈgaŋ-ˌpɝt
    ˈmɝdʒ-ˌnɛt
    ˈɔ-vɛɹ-ˌjeːɔ-tan
    ˈɪɹmθ
    ˈmeː-zə
    ˈwiːt-nʌŋ-ˌstoː
    jɛ-ˈmɛt-ˌfæst-nɛs
    ˈwɪ-tʃa
    ˈla-gʌ-ˌfæ-θəm
    ˈmɛ-ɹə-ˌweː-ɹɪj
    ˈsʌnd-ˌwʌ-dʌ
    ˈbɹɪm-ˌwiː-za
    ˈɹeː-nɪj
    ˈhoːp-jɛ-ˌhnaːst
    ˈhlæd-ˌhwɛɔl
    ˈuː-ɹɪj-ˌfɛ-θɛ-ɹa
    ˈnɪ-kɔɹ
    ˈswan-ˌɹaːd
    ˈla-gʌ
    jɛ-ˈswɛɔk
    ˈfant-ˌwæ-tɛɹ
    ˈsɛɔlh-ˌɝː-θa
    ˈga-nɔt
    ˈwæ-tɛɹ
    ˈgɹɪst-ˌbɪ-tʌŋ
    ˈaːɹ-ˌfæst-lɪtʃ
    ˈfɹɝmθ
    ˈeːa-dɪj-nɛs
    ʌn-ˈa-wɛn-dɛd-liːtʃ
    ˈtʃeːp
    ˈθʌ-nɔɹ
    ˈleː-jɛ-tʌ
    ˈhɹæ-dɪŋ
    ˈgɔ-mɛn-ˌwaː-θʌ
    ˈwɛ-ɹə-ˌwʌlf
    ˈmuː-θɛt-tan
    ˈgɔŋ-gɛl-ˌwæv-rə
    jɛ-ˈɛd-ˌkʌ-tʃɪ-an
    ˈwɛɹ-ˌjɪld
    ˈfɝɹh-tɔ
    ˈwiːj-ˌbɛd
    ˈeːa-laː
    ʌn-ˈdeːaθ-liː
    ˈduː-ɹʌ-ˌwɛaɹd
    ˈnɛɔ-wɔl-nɛs
    jɛ-ˈdwɔ-la
    ˈɛaɹ-vɔθ-ˌɹɛ-tʃə
    ˈsɝ-pɪ-an
    ˈboːk
    ˈsoːθ-ˌkwɪ-də
    ˈdeːɔ-vɔl-ˌjɪld
    ˈwɪn-dɛl-ˌstaːn
    ˈhɹæd-liːtʃ
    ˈblɝw-nɝs
    ˈfɹɔm-ˌʃɪ-pə
    ˈɔɹ-ˌmoːd
    ˈiː-zɛɹn
    ˈʌn-aː-ˌsɛdʒ-ɛnd-liːtʃ
    ˈɛn-də-ˌdæj
    ˈeː-θə-ˌliː-tʃə
    ˈbɛd-ˌklɝː-va
    ɛl-ˈɹɛɔɹ-dɪj
    ɔn-ˈbɹɛj-dan
    ˈneːah-ˌmʌnt
    ɔn-ˈjɪ-tan
    ˈkwɪtʃ
    ˈsɪ-ɹʌ-ˌtuːn
    ˈtiːd-ˌliː-tʃə
    ˈɛɔɹθ
    ˈda-jɪ-an
    ˈeːa-stɛɹ
    a-ˈleː-zan
    ˈɹoːd
    ˈæː-vɛn-jɛ-ˌɹɛɔɹd
    ˈliːtʃ-ˌθɹɔ-wɛ-ɹə
    ˈkwɛ-θan
    ˌa-ˈwɛɾg-ɪ-an
    ˈdɹɪh-tɛn-ˌliːtʃ
    ˌa-ˈwɛk-kan
    ˈæʃ
    ˈwɔɹd-ˌsnɔ-tɔɹ
    ˈbɛd-dɪŋ
    ʌn-ˈɹeː-tʌ
    ˈswæː-zɛn-dʌ
    jɛ-ˈsɝn-tɔ
    ˈkɝs-san
    ˈhaːl-zɪ-an
    ˈlɝt-lɪŋ
    ˈeːɔ-ɹɔd-ˌman
    jɛ-ˈlaː-kan
    ˈklɝp-pan
    ˈgɔd-ˌspɹɛtʃ
    ʌn-ˈɔ-vɛɹ-ˌswiː-θɛd
    ˈjeːɔm-ɹʌŋ
    ˈhnʌ-tʌ
    ˈɪɹ-və-ˌwɛaɹd-nɛs
    ˈwɝɹd-ˌwɹɪ-tɛ-ɹə
    ˈʃeːɔ
    ˈjɛɔk-sa
    ˈæːj-hwæt
    ˈɹeː-tʃɛls
    ˈlɝb-ˌlaːk
    ˈswɛaɹt
    ˈgɹæːj-ˌha-ma
    ˈhaːl-ga
    jɛ-ˈnɪht-ˌsʌm-nɛs
    ˈlaːd-ˌteːɔ
    ˈhɛalz-ˌbeːag
    ˈdɹʌnk-ɛn-ˌlæː-wə
    ˈsɛalm-ˌwɝɹh-ta
    ˈwɝɹt-jɛ-ˌmaŋ
    ˈdwɪ-mɔɹ-ˌliː-tʃə
    jɛ-ˈθeːɔ-də
    ˈhɝ-ʃan
    ˈdɹæj-ˌnɛt
    ˈɛɔɹk-nan-ˌstaːn
    ˈhwæt-ˌhwɛ-ga
    ˈmæːɹ-liːtʃ
    ˈgɔd-ˌmæ-jɛn
    ˈθuː-zɛnd
    ˈaː-sɛ-jɛnd-nɛs
    ˈhoːh
    jɛ-ˈsʌnd
    ˈsɝm-bɛl-ˌwlank
    ˈsɪ-θan
    ˈdɛ-nə
    jɛ-ˈhlɛɔ
    ˈdeːɔɹ-ˌwɝɹ-θə
    ˈhank-ˌɹeːd
    jɛ-ˈniː-pan
    ˈwiːtʃ-ˌstoː
    ˈfɛ-θɛɹ-ˌfoː-tə
    jɛ-ˈsɔm-nɪ-an
    ˈhɪl-də-ˌspɛl
    ʌn-ˈhiːɹ-liːtʃ
    ˈlʌ-vɪ-an
    ˈkɹɔp-ˌleːak
    ˈmɔ-ɹə
    ˈhʌ-nɪj
    ˈfiːtʃ-ˌæp-pɛl
    ˈkɹɔh
    ˈpɛɹ-sɔk
    ˈɔ-stɹə
    jɛ-ˈtɛld
    ˈdæj-ˌwɛɔrk
    ˈfa-stɪ-tɔ-ˌka-lɔn
    ˈɔ-næː-lan
    ˈlaː-ɹeːɔ
    ˈlɛɔɹ-nʌŋ-ˌknɪht
    ˈwɛaɹg
    ˈfleːa
    ˈʌp-ˌgaŋ
    ˈflaːn-jɛ-ˌwɛɔɹk
    ˈflæːʃ-ˌstɹæːt
    ˈgɹiːj-ˌhʌnd
    ˈmaː-ga-ˌθiːht
    ˈuːht-ˌtʃɛa–ɹʌ
    ˈbɛa-dʌ-ˌgɹiː-ma
    ˈand-ˌwɛɔɹk
    ˈʌn-dɛɹ-ˌsmuː-gan
    ˈtʃɝːz-ˌwʌ-tʃə
    ˈsʌn-nan-ˌdæj
    ˈsæ-tɛɹn-ˌdæj
    ˈfɹɪj-ˌdæj
    ˈθuː-ɹəz-ˌdæj
    ˈwoːd-nəz-ˌdæj
    ˈtiː-wəz-ˌdæj
    ˈmoː-nan-ˌdæj
    ˈuːθ-ˌwɪ-tɪ-gʌŋ
    ˈfloːd-ˌɛj-za
    ˈsaː-wɛl-ˌdɹeːɔɹ
    ˈhɛa-θʌ-ˌswaːt
    ˈfɝːɹ-ˌbæθ
    ˈand-leːan
    ˈfɛɹθ-ˌweː-ɹɪj
    ˈɔɹ-θank
    ˈeːa-jɛ-ˌbɝɹd
    ˈlɛaks
    ˈa-ɹɔd-nɛs
    ˈhɛŋ-gɛst
    ˈɛd-nɪ-wɪ-an
    ˈjeːaɹ-ˌda-gʌm
    fɹeːɔl-zɪ-an
    ˈswɛ-van
    ˈsɪ-jə-ˌbeːam
    ˈwɪn-tɛɹ–jɛ-ˌwæː-dɛ
    ˈkɹɪs-təs-ˌmæs-sə
    ˈwɪn-tɛɹ-ˌfɛɔɹm
    ˈjeːɔl
    ˈælf
    ˈmɪd-ˌwɪn-təɹ ˈmoː-naθ
    ˈfɹeːɔnd-ˌʃɪ-pə
    ˈleːɔ-θʌ-ˌkɹæft
    ˈbɹeːɔst-ˌlɔ-ka
    ˈmɛ-ɹə-ˌdeːɔɹ
    ˈniːd-ˌbɔ-da
    ˈtɔɹht
    ˈkluː-stɔɹ-ˌkleːɔ-va
    ˈhɛaɹd-ˌsæː-lɪj
    ˈθeːɔ-dɛn
    ˈfɜɹn-jɛ-ˌwɹɪt
    ˈfæːɹ-ˌfɝl
    ˈwɪ-nə-ˌtɹeːɔ
    ˈhɹɪŋ-əd-ˌstɛv-na
    ˈnɛa-ɹʌ-ˌθɛaɹf
    ˈɔɹk
    ˈɔɹk-ən
    ˈɝːθ-jɛ-ˌbland
    ˈdiː-gɔl
    ˈdɹɝht-sɛ-lə
    ˈbaːn-ˌhuːs
    ˈfeːɔnd-ˌʃɪ-pə
    ˈhlɛah-tɔɹ
    ˈθɪŋ
    ˈhwæt
    bɝ-ˈsmɛ-ɹɪ-an
    ˈfneːɔ-zan
    ˈʌn-ˌjeːa-ɹa
    ˈbɛt-liːtʃ
    ˈhand-jɛ-ˌwɛɔɹk
    ˈɹuːn-ˌstæf
    ˈʃɪp-pɛnd
    ˈwɝɹm
    ˈnɛɔrk-sna-ˌwaŋ
    ˈsnɔ-tɔɹ
    ˈkɔl-lɛn-ˌfɛɹhθ
    ˈhɛɔ-vɔn-ˌkan-dɛl
    ˈʃɛa-dʌ-ˌjɛŋ-ga
    ˈhɹeːa-θə-ˌmuːs
    ˈfaː
    ˈwɔɹd-ˌhɔɹd
    """
}
